apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-test-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-test-service
  template:
    metadata:
      labels:
        app: devops-test-service
    spec:
      containers:
      - name: devops-test-service
        image: teazer/devops-test-service:latest
        ports:
        - containerPort: 8080