apiVersion: v1
kind: Service
metadata:
  name: devops-test-service-lb
spec:
  type: LoadBalancer
  selector:
    app: devops-test-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080